const $ = (s, scope = document) => scope.querySelector(s);
const engineStorageKey = 'freenav-visible-engines-v1';
let data;
const detectedLocale = (navigator.languages || [navigator.language || 'en']).some(x => x.toLowerCase().startsWith('zh')) ? 'zh' : 'en';
let locale = localStorage.getItem('freenav-locale') || detectedLocale;
const fallbackCopy = { zh: { brand: '巡航', footer: '一个更从容的<br>网页起点。', search: '搜索', query: '输入任何想找的事物', editSearch: '编辑搜索', searchHome: '主页搜索', chooseEngines: '选择搜索引擎', searchDescription: '勾选要显示在主页上的搜索引擎。列表第一项会成为默认搜索。', showOnHome: '显示在主页上', save: '保存', cancel: '取消', common: '常用入口', legal: '收录平台均指向其官方网站。免费资格与使用范围以各平台当前条款为准。', noEngine: '请至少保留一个搜索引擎。' }, en: { brand: 'FreeNav', footer: 'A calmer<br>place to begin.', search: 'Search', query: 'Search for anything', editSearch: 'Edit search', searchHome: 'Homepage search', chooseEngines: 'Choose search engines', searchDescription: 'Choose the engines shown on your homepage. The first becomes your default search.', showOnHome: 'Show on homepage', save: 'Save', cancel: 'Cancel', common: 'Everyday essentials', legal: 'All links point to official platforms. Free access and usage terms are subject to each provider’s current policy.', noEngine: 'Keep at least one search engine selected.' } };
const t = key => (data?.ui?.[locale] || data?.ui?.en || fallbackCopy[locale])[key] || fallbackCopy[locale][key] || key;
const local = (item, key) => item[`${key}${locale === 'zh' ? 'Zh' : 'En'}`] || (locale === 'en' && key === 'description' ? 'A trusted legal online resource.' : '') || (locale === 'en' && key === 'tag' ? 'Resource' : '') || item[key] || '';

function loadVisibleEngines() { try { const saved = JSON.parse(localStorage.getItem(engineStorageKey)); if (Array.isArray(saved) && saved.length) return saved.filter(id => data.searchEngines.some(engine => engine.id === id)); } catch {} return ['google', 'bing', 'brave', 'duckduckgo']; }
function visibleEngines() { return loadVisibleEngines().map(id => data.searchEngines.find(engine => engine.id === id)).filter(Boolean); }
function renderLanguages() { $('#languageSelect').innerHTML = data.languages.map(language => `<option value="${language.id}" ${language.id === locale ? 'selected' : ''}>${language.label}</option>`).join(''); }
function renderNav(pageId) { $('#nav').innerHTML = data.pages.map(page => `<a class="nav-item ${page.id === pageId ? 'active' : ''}" href="#${page.id}"><span class="nav-icon">${page.icon}</span>${local(page, 'title')}</a>`).join(''); }
function card(link) { const fragment = $('#linkCard').content.cloneNode(true); $('.link-card', fragment).href = link.url; $('.link-mark', fragment).textContent = link.mark; $('.link-copy b', fragment).textContent = link.name; $('.link-copy small', fragment).textContent = local(link, 'description'); $('.tag', fragment).textContent = local(link, 'tag'); return fragment; }
function renderCards(pageId, container) { data.links.filter(link => link.page === pageId).forEach(link => container.append(card(link))); }

function renderHome(page) {
  const engines = visibleEngines(); const defaultEngine = engines[0];
  $('#app').innerHTML = `<section class="page"><header class="heading"><p class="eyebrow">${local(page, 'eyebrow')}</p><h1>${local(page, 'headline')}</h1><p>${local(page, 'description')}</p></header><section class="search-panel"><form id="searchForm"><div class="search-row"><input class="search-box" id="query" autocomplete="off" autofocus placeholder="${t('query')}" aria-label="${t('query')}"><button class="primary-btn" type="submit">${t('search')} · ${defaultEngine.name}</button></div></form><div class="engine-actions">${engines.slice(1).map(engine => `<button class="engine-search" type="button" data-engine="${engine.id}"><i class="engine-dot" style="background:${engine.tone}"></i>${engine.name}</button>`).join('')}<button class="edit-link" id="editEngines">${t('editSearch')}</button></div></section><section><h2 class="section-title">${t('common')}</h2><div class="link-grid" id="links"></div></section></section>`;
  renderCards('home', $('#links')); $('#searchForm').addEventListener('submit', event => search(event, defaultEngine.id)); document.querySelectorAll('[data-engine]').forEach(button => button.addEventListener('click', () => search(null, button.dataset.engine))); $('#editEngines').addEventListener('click', openSearchDialog);
}
function renderResource(page) { $('#app').innerHTML = `<section class="page"><header class="heading"><p class="eyebrow">${local(page, 'eyebrow')}</p><h1>${local(page, 'headline')}</h1><p>${local(page, 'description')}</p></header><p class="resource-note">${t('legal')}</p><section><div class="link-grid" id="links"></div></section></section>`; renderCards(page.id, $('#links')); }
function render() { const id = location.hash.slice(1) || 'home'; const page = data.pages.find(item => item.id === id) || data.pages[0]; renderNav(page.id); page.id === 'home' ? renderHome(page) : renderResource(page); document.title = `${local(page, 'title')} — FreeNav`; }
function applyLocale(nextLocale) { locale = nextLocale; localStorage.setItem('freenav-locale', locale); document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en'; $('.brand span:last-child').textContent = t('brand'); $('#sidebarFooter').innerHTML = t('footer'); $('#languageSelect').value = locale; $('#searchEyebrow').textContent = t('searchHome'); $('#searchDialogTitle').textContent = t('chooseEngines'); $('#searchDialogCopy').textContent = t('searchDescription'); $('#engineLegend').textContent = t('showOnHome'); $('#cancelSearchSettings').textContent = t('cancel'); $('#saveSearchSettings').textContent = t('save'); render(); }
function search(event, engineId) { event?.preventDefault(); const query = $('#query').value.trim(); if (!query) { $('#query').focus(); return; } const engine = data.searchEngines.find(item => item.id === engineId); if (engine) window.open(engine.url.replace('{query}', encodeURIComponent(query)), '_blank', 'noopener'); }
function openSearchDialog() { const selected = loadVisibleEngines(); $('#enginePicker').innerHTML = data.searchEngines.map(engine => `<label class="engine-option"><input type="checkbox" value="${engine.id}" ${selected.includes(engine.id) ? 'checked' : ''}><i class="engine-dot" style="background:${engine.tone}"></i>${engine.name}</label>`).join(''); $('#searchDialog').showModal(); }
function saveSearchSettings(event) { event.preventDefault(); if (event.submitter?.value === 'cancel') { $('#searchDialog').close(); return; } const selected = [...document.querySelectorAll('#enginePicker input:checked')].map(input => input.value); if (!selected.length) { showToast(t('noEngine')); return; } localStorage.setItem(engineStorageKey, JSON.stringify(selected)); $('#searchDialog').close(); render(); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 3800); }
async function init() { data = await fetch('data/resources.json').then(response => response.json()); if (!data.languages.some(language => language.id === locale)) locale = 'en'; renderLanguages(); $('#languageSelect').addEventListener('change', event => applyLocale(event.target.value)); $('#searchSettingsForm').addEventListener('submit', saveSearchSettings); window.addEventListener('hashchange', render); applyLocale(locale); }
init();
